### ISSUE TITLE
Write July newsletter

### ISSUE THREAD

**Issue by opetchey** [ResponseDiversityNetwork/RDN-website#13]
posts/2023-07-01-Newsletter-July2023.qmd

Is in draft mode, so not live.

**Comment by SamRPJRoss** [comment]
I edited and added some bits to the end. The one part I didn't edit was the first section about the scope of new membership. @opetchey would you mind please writing that part if you don't mind? Else I can do it, too (but feel you'd do a more eloquent job on that one!) 

Thanks, Sam

**Comment by opetchey** [comment]
Hi Sam, thanks, and yep, I'll very happily do that :) Cheers, Owen

**Comment by opetchey** [comment]
@SamRPJRoss Hi Sam, please take a look at the newsletter now (including close proof-read) and the other two revised pages in my latest commit.

**Comment by SamRPJRoss** [comment]
Thanks Owen, I just made very minor edits following a close proof read of the newsletter and two pages (about and who-we-are). Thanks for your edits, this all looks great now and I'm happy for this to be the final version whenever you are.

**Comment by opetchey** [comment]
OK, the newsletter and other updates are live. Will you send an email to the network with the newsletter?

**Comment by SamRPJRoss** [comment]
Thanks Owen! I sent a link to the newsletter, and Shyamolina pointed out we misspelled her name (oops). I'm not now 100% sure where to fix it, so would you mind please just correcting the spelling of her name in the newsletter and pushing it straight to the live branch? Thanks so much (sorry I can't see where to do it!)

**Comment by opetchey** [comment]
Should be done now or very soon.

**Comment by SamRPJRoss** [comment]
Thanks Owen :)
