### ISSUE TITLE
make an interactive map

### ISSUE THREAD

**Issue by opetchey** [ResponseDiversityNetwork/RDN-website#16]

**Comment by opetchey** [comment]
@SamRPJRoss @CeresBarros 

Done with google maps and put on [this page](https://responsediversitynetwork.github.io/RDN-website/who-we-are.html).

I added some cities to [the member list that I put in a google sheet](https://docs.google.com/spreadsheets/d/1eADeWvINTP9AK9c1z91CvhFvd7pQOEn9lmd0W7LY1kY/edit?usp=sharing). Works well. Just need to go through the rest. We should only use this google sheet member list now. (I made inactive the member list spreadsheet in the private github repo. We should only use the google sheet one now.)

**Comment by CeresBarros** [comment]
This looks great! Just to clarify, the google sheet will be maintained by us, or will members populate it?

**Comment by CeresBarros** [comment]
Another question: does it make sense to keep the static (and out-of-date) map on the welcome page?

**Comment by opetchey** [comment]
I made new issues of your questions
