### ISSUE TITLE
remove published date on pages (but not posts)

### ISSUE THREAD

**Issue by opetchey** [ResponseDiversityNetwork/RDN-website#22]
I think its not done yet.

**Comment by CeresBarros** [comment]
@opetchey can you point me to where a date is still showing? The only one i see is the one on the [Welcome page](https://responsediversitynetwork.github.io/RDN-website/), which I'm not sure how to remove (I think it's automatically added because the page shows the "news" feed (AKA posts) ?)

**Comment by CeresBarros** [comment]
Ah I see it everywhere now. Strange I could swear my initial solution was working.

**Comment by opetchey** [comment]
Looks good now. Thank you.
