### ISSUE TITLE
New post not being published

### ISSUE THREAD

**Issue by opetchey** [ResponseDiversityNetwork/RDN-website#26]
@CeresBarros Dear Ceres, please would you have a look at why the post I just made is not being published? It is in this commit: https://github.com/ResponseDiversityNetwork/RDN-website/commit/4203cfca96f91565c55c481e6c190c6b10212ce5 

Thanks and all the best
Owen

**Comment by CeresBarros** [comment]
two issues:
- `draft: true` in YAML header -> this was causing the post to be ommitted
- the date had 2023 instead of 2024

All fixed now :)

**Comment by opetchey** [comment]
Aaaaaaaaarg!
Thank you!
