### ISSUE TITLE
Add appropriate dates appropriately!

### ISSUE THREAD

**Issue by opetchey** [ResponseDiversityNetwork/RDN-website#7]
We could add the date it to each page. I think the following would work:

---
title: About
date: last-modified
date-format: long
---

**Comment by CeresBarros** [comment]
On it -- will not modify blog post pages though, as those dates should be "fixed"

**Comment by CeresBarros** [comment]
Footer date is now updated automatically for every page.
83e6f34310b2e33b575c4b3739b08ffd24f5fd62.
