### ISSUE TITLE
Make the logo in the navbar bigger, remove logo in sidebar

### ISSUE THREAD

**Issue by opetchey** [ResponseDiversityNetwork/RDN-website#8]
But its not so easy to figure out how to make the logo in the navbar bigger

**Comment by taddallas** [comment]
Oh nice. I think I did this (before reading this issue), in [this pull request](https://github.com/ResponseDiversityNetwork/RDN-website/pull/11). The code for the navbar logo to be bigger is in there-ish, but I'd need to look at it again, as I remember making it bigger and the navbar text getting shifted in a weird way. Sidebar is gone in that PR.

**Comment by opetchey** [comment]
@taddallas I made it bigger, but there is still a small version there at the same time. Weird. Not sure where that's coming from! (Working in dev1 branch.)

**Comment by CeresBarros** [comment]
FYI the small logo was a `logo:` field in `_quarto.yml`
